use wasm_bindgen::prelude::wasm_bindgen;
use web_sys::console::log_1 as log;

// web_sys crate exports JavaScript functions defined by the browser
// wasm_bindgen crate exports functions created / generated by the developer
#[wasm_bindgen]
pub fn grayscale(encoded_file: &str) {
   log(&encoded_file.into()); // into() is used to convert a str into a JavaScript value
}
